chore(staging) Prep manifests to interact with staging
- [x] Terragrunt
- [x] formatting for best practices (count, for_each, depends_on, etc)
- [x] handle multiline ternaries (wrap in parenthesis)
- [x] setup staging2
- [x] remove admin
- [x] drop python script and use yq to check keys
- [x] update secrets example
- [x] update docs
- [x] change debugger image to include psql v13 to match database so pgdump can work
- [x] change all things to staging instead of test

diff --git a/terraform/Makefile b/terraform/Makefile
--- a/terraform/Makefile
+++ b/terraform/Makefile
@@ -1,4 +1,4 @@
-ENV ?= test
+ENV ?= staging
 
 define ecs_ssh
 	aws --profile jump${ENV} \
@@ -11,8 +11,19 @@ define ecs_ssh
 		--interactive
 endef
 
+define keys_diff
+	yq '(.$(1)_secrets | keys)-.$(1)_secrets_keys' env/${ENV}/$(1).secrets.${ENV}.yaml
+endef
+
+define b64e_secrets
+	cat env/${ENV}/$(1)/$(1).secrets.${ENV}.yaml | base64 | pbcopy
+endef
+
 .PHONY : help
 help: # Display help
+	@echo "Usage: make [target] [ENV=staging]"
+	@echo "Default ENV is staging"
+	@echo "targets:"
 	@awk -F ':|##' \
 		'/^[^\t].+?:.*?##/ {\
 			printf "\033[36m%-30s\033[0m %s\n", $$1, $$NF \
@@ -22,64 +33,85 @@ help: # Display help
 env: ## Echo out environment
 	@echo $(ENV)
 
-.PHONY : validate
-validate: ## Terraform validate
-	@terraform validate
+.PHONY : clearcache
+clearcache: ## Clear Terragrunt cache
+	@find . -type d -name ".terragrunt-cache" -exec rm -rf {} ";"
 
-.PHONY : lint
-lint: ## Run tflint
-	@tflint --init && \
-	while read line; do \
-      tflint $$line --var-file="secrets.${ENV}.tfvars.json" \
-				--var-file="envvars.${ENV}.tfvars.json"; \
-    done < "tflint-enabled-directories";
+.PHONY : validate
+validate: ## Terragrunt validate
+	cd env/${ENV} && \
+	export AWS_PROFILE=jump${ENV} && \
+	terragrunt run-all validate
+
+.PHONY : api_keys
+api_keys: ## Validate secret api keys list matches api keys in sensitive map
+	@if [ $(shell $(call keys_diff,api) | yq length) -gt 0 ]; then \
+		echo "ERROR: api_secrets_keys does not match api_secrets keys" && \
+		$(call keys_diff,api) && \
+		exit 1; \
+	fi
+
+.PHONY : web_keys
+web_keys: ## Validate secret web keys list matches web keys in sensitive map
+	@if [ $(shell $(call keys_diff,web) | yq length) -gt 0 ]; then \
+		echo "ERROR: web_secrets_keys does not match web_secrets keys" && \
+		$(call keys_diff,web) && \
+		exit 1; \
+	fi
+
+.PHONY : secrets
+secrets: ## Generate secrets from templates
+	$(eval API_FILE := env/$(ENV)/api.secrets.$(ENV).yaml)
+	$(eval WEB_FILE := env/$(ENV)/web.secrets.$(ENV).yaml)
+	@if [ ! -f "$(API_FILE)" ]; then cp api.secrets.template.yaml $(API_FILE); fi
+	@if [ ! -f "$(WEB_FILE)" ]; then cp web.secrets.template.yaml $(WEB_FILE); fi
 
 .PHONY : keys
-keys: ## Validate secret keys list matches keys in sensitive map
-	@python3 ../scripts/check_secrets.py ${ENV}
+keys: api_keys web_keys ## Run key checks
 
 .PHONY : check
-check: lint validate keys ## Run some checks
+check: validate keys ## Run some checks
 
 .PHONY : show
-show: ## Show Terraform
-	terraform show -json | jq .
+show: ## Show Terragrunt
+	terragrunt show -json | jq .
 
-.PHONY : b64e_secrets
-b64e_secrets: ## Base64 encode secrets to be stored in GitHub secrets for CI
-	cat secrets.${ENV}.tfvars.json | base64 | pbcopy
+.PHONY : b64e_api_secrets
+b64e_api_secrets: ## Base64 encode API secrets to be stored in GitHub secrets for CI
+	$(call b64e_secrets,api)
+
+.PHONY : b64e_web_secrets
+b64e_web_secrets: ## Base64 encode WEB secrets to be stored in GitHub secrets for CI
+	$(call b64e_secrets,web)
+
+.PHONY : b64e_all_secrets
+b64e_all_secrets: b64e_api_secrets b64e_web_secrets ## Base64 encode secrets to be stored in GitHub secrets for CI
 
 .PHONY : console
-console: ## Terraform console
-	terraform console -var-file="secrets.${ENV}.tfvars.json" \
-		-var-file="envvars.${ENV}.tfvars.json"
+console: ## Terragrunt console
+	terragrunt console
 
 .PHONY : init
-init: ## Initialize Terraform
+init: ## Run Terragrunt Init
+	cd env/${ENV} && \
 	export AWS_PROFILE=jump${ENV} && \
-	terraform init -var-file="secrets.${ENV}.tfvars.json" \
-		-var-file="envvars.${ENV}.tfvars.json" \
-		-backend-config=$(ENV).tfbackend
+	terragrunt init
 
 .PHONY : plan
-plan: ## Run Terraform Plan
+plan: ## Run Terragrunt Plan
+	cd env/${ENV} && \
 	export AWS_PROFILE=jump${ENV} && \
-	terraform plan -var-file="secrets.${ENV}.tfvars.json" \
-		-var-file="envvars.${ENV}.tfvars.json"
+	terragrunt run-all plan
 
 .PHONY : apply
-apply: ## Run Terraform Apply
+apply: ## Run Terragrunt Apply
+	cd env/${ENV} && \
 	export AWS_PROFILE=jump${ENV} && \
-	terraform apply -auto-approve -var-file="secrets.${ENV}.tfvars.json" \
-		-var-file="envvars.${ENV}.tfvars.json"
+	terragrunt run-all apply -auto-approve
 
 .PHONY : api
 api: ## SSH onto ECS API instance
 	$(call ecs_ssh,api)
-
-.PHONY : admin
-admin: ## SSH onto ECS Admin instance
-	$(call ecs_ssh,admin)
 
 .PHONY : web
 web: ## SSH onto ECS Web instance
